// 12 הקוקטיילים מהתפריט. אחוזי האלכוהול, הבסיס והמרכיבים לקוחים מקובץ המינונים של בעל העסק.
// תמונה: images/cocktails/<slug>.jpg  (אם הקובץ קיים הוא יחליף את הרקע הצבעוני)
// תיאורים: טון רציני עם נגיעה שנונה; כל טענה מבוססת על המרכיבים בקובץ המינונים.
const SHAKE = 'נערו קלות לפני הפתיחה, ומזגו על קרח.';

export const COCKTAILS = [
  { slug: 'margarita', he: 'מרגריטה', en: 'Margarita', base: 'טקילה', abv: 26,
    taste: ['חמצמץ', 'הדרי'], colors: ['#E8EFA6', '#B9CF5A'], serve: SHAKE,
    desc: 'טקילה, לימון וטריפל סק. שלושה מרכיבים, אפס פשרות.' },
  { slug: 'watermelon-margarita', he: 'מרגריטת אבטיח', en: 'Watermelon Margarita', base: 'טקילה', abv: 23,
    taste: ['פירותי', 'חמצמץ'], colors: ['#FFB3B8', '#F0566A'], serve: SHAKE,
    desc: 'מרגריטה שיצאה לחופשה: טקילה, ליים וסירופ אבטיח.' },
  { slug: 'watermelon-sugar', he: 'וואטרמלון שוגר', en: 'Watermelon Sugar', base: 'רום', abv: 21,
    taste: ['מתוק', 'פירותי'], colors: ['#FFC9D1', '#F37C93'], serve: SHAKE,
    desc: 'רום, אבטיח ולימון. מתוק מספיק כדי לחייך, קליל מספיק כדי לשתות לאט.' },
  { slug: 'tequila-sunrise', he: 'טקילה סאנרייז', en: 'Tequila Sunrise', base: 'טקילה', abv: 13.5,
    taste: ['מתוק', 'הדרי'], colors: ['#FFC24A', '#E8452C'], serve: SHAKE,
    desc: 'טקילה, תפוזים וגרנדין. הזריחה היחידה שכדאי להישאר ערים בשבילה.' },
  { slug: 'bluebedy', he: 'בלובדי', en: 'Bluebedy', base: 'טקילה', abv: 13.5,
    taste: ['פירותי', 'מבעבע'], colors: ['#9DA7F2', '#4B4FB5'],
    serve: 'אל תנערו – יש בו סודה. פתחו בעדינות ומזגו על קרח.',
    desc: 'פסיפלורה ואוכמניות על טקילה, עם סודה שמוסיפה בועות. מבעבע, בלי שייקר.' },
  { slug: 'peach-perfect', he: 'פיץ׳ פרפקט', en: 'Peach Perfect', base: 'וודקה', abv: 16.5,
    taste: ['מתוק', 'קרמי'], colors: ['#FFE0C2', '#F7A777'], serve: SHAKE,
    desc: 'וודקה, אפרסק ולימון, וקרם קוקוס שמוסיף קטיפה. עדין למראה, אבל זה עדיין קוקטייל.' },
  { slug: 'pineapple-wave', he: 'פיינאפל וויב', en: 'Pineapple Wave', base: 'וודקה', abv: 18,
    taste: ['מתוק', 'טרופי'], colors: ['#7FE0C8', '#14A38B'], serve: SHAKE,
    desc: 'וודקה, אננס ובלו קורסאו בגוון טורקיז. חופשה בלי טיסה.' },
  { slug: 'fine-and-dandy', he: 'פיין אנד דאנדי', en: 'Fine and Dandy', base: 'ג׳ין', abv: 24.5,
    taste: ['הדרי', 'חמצמץ'], colors: ['#F6EBC0', '#D7BE6C'], serve: SHAKE,
    desc: 'ג׳ין, לימון וטריפל סק. חד, הדרי ואלגנטי – כמו חליפה תפורה.' },
  { slug: 'cosmopolitan', he: 'קוסמופוליטן', en: 'Cosmopolitan', base: 'וודקה', abv: 20,
    taste: ['חמצמץ', 'פירותי'], colors: ['#FFB8CF', '#D93A74'], serve: SHAKE,
    desc: 'וודקה, חמוציות וליים. הוורוד שלא צריך להסביר את עצמו.' },
  { slug: 'israeli-sunset', he: 'שקיעה ישראלית', en: 'Israeli Sunset', base: 'וודקה וערק', abv: 16,
    taste: ['מרענן', 'פירותי'], colors: ['#FFD27A', '#E56A8B'], serve: SHAKE,
    desc: 'וודקה וערק עם לימונדה ונגיעת אוכמניות. שקיעה בלי פקקים.' },
  { slug: 'strawberry-sour', he: 'סאוור תות', en: 'Strawberry Sour', base: 'וויסקי', abv: 19.2,
    taste: ['חמצמץ', 'פירותי'], colors: ['#FFB5BE', '#E0364E'], serve: SHAKE,
    desc: 'וויסקי, לימון וסירופ תות. מי אמר שוויסקי לא יכול להיות פירותי?' },
  { slug: 'sunset-kiss', he: 'סאנסט קיס', en: 'Sunset Kiss', base: 'וודקה', abv: 16.6,
    taste: ['טרופי', 'מתוק'], colors: ['#FFD9B0', '#F28A5B'], serve: SHAKE,
    desc: 'וודקה, שנאפס אפרסק, תפוזים וחמוציות. נשיקה טרופית – קלילה, מתקתקה וללא התחייבות.' },
];
